Update .versions and .exp for cFMS
flybywiresim/discord-bot pull request #14
Opened 2021-08-20 19:14 UTC by NUTTTTTTTT

Now experimental is back in use with cFMS - updated bot commands for .exp and .versions accordingly.

2021-08-20 20:49 UTC, FoxtrotSierra6829 approved these changes

2021-08-20 21:53 UTC, NUTTTTTTTT commented
Added https://docs.flybywiresim.com/start/fbw-versions/ to .versions for a deeper comparison

2021-08-21 17:20 UTC, ZigTag requested changes
Please rewrite line 29

2021-08-21 17:20 UTC, ZigTag commented on src/commands/versions.ts
> +                value: '> This version is similar to the development version, but contains custom systems in progress, including the new FBW Custom Flight Management System (cFMS). '
Worded weirdly

2021-08-21 17:33 UTC, ZigTag requested changes

2021-08-21 17:33 UTC, ZigTag commented on src/commands/versions.ts
> +                        + 'Experimental version will be updated with the latest changes to the "custom-fpm" branch and development version regularly. '
It pulls from the experimental branch, not the autopilot-custom-fpm one.

2021-08-21 17:45 UTC, ZigTag approved these changes
LGTM

2021-08-21 17:45 UTC, merged