feat: add manual command
flybywiresim/discord-bot pull request #144
Opened 2022-01-03 20:44 UTC by xZreai

## Description

adds manual command to support category

## Test Results
![image](https://user-images.githubusercontent.com/81078099/147978394-ec1f557a-7550-41f5-8c9f-6d94031ccba5.png)

## Discord Username

Cleon#5802

2022-01-03 20:54 UTC, benw202 requested changes

2022-01-03 20:54 UTC, benw202 commented on src/commands/support/manual.ts
> +    category: CommandCategory.A32NX,
```suggestion
    category: CommandCategory.SUPPORT,
```

You have added this to the support category (at least in folder structure), so we need to define this here too.

2022-01-03 20:54 UTC, benw202 commented on src/commands/support/manual.ts
> +        image: { url: MANUAL_URL } })),
```suggestion
        image: { url: MANUAL_URL }, 
    })),
```

Just some formatting

2022-01-03 21:15 UTC, xZreai commented
oop didn't mean to request review

2022-01-03 21:41 UTC, benw202 requested changes

2022-01-03 21:41 UTC, benw202 commented on src/commands/support/manualleg.ts
> +    category: CommandCategory.A32NX,
```suggestion
    category: CommandCategory.SUPPORT,
```

2022-01-06 02:27 UTC, Earthsam12 commented
Can you use the [new image](https://docs.flybywiresim.com/pilots-corner/advanced-guides/flight-planning/disco/?h=manual#illustrations-for-manual-legs) by mav?

2022-01-07 18:02 UTC, xZreai commented
> Can you use the [new image](https://docs.flybywiresim.com/pilots-corner/advanced-guides/flight-planning/disco/?h=manual#illustrations-for-manual-legs) by mav? And maybe link to that page in the footer too?

Yep done

2022-01-07 18:03 UTC, xZreai commented
Can I get any ideas for what the text description for this command would be?

2022-01-07 18:52 UTC, Earthsam12 requested changes
remove some out of place whitespace and also shorten the line so that vsc doesn't yell at you

2022-01-07 18:52 UTC, Earthsam12 commented on src/commands/support/manualleg.ts
> +
```suggestion
const DISCON_DOCS_URL = 'https://docs.flybywiresim.com/pilots-corner/advanced-guides/flight-planning/disco/?h=manual#discontinuities-after-manual-leg';

```

2022-01-07 18:52 UTC, Earthsam12 commented on src/commands/support/manualleg.ts
> +    name: ['manualleg','vm'],
```suggestion
    name: ['manualleg', 'vm'],
```

2022-01-07 18:52 UTC, Earthsam12 commented on src/commands/support/manualleg.ts
> +    executor: (msg) => msg.channel.send(makeEmbed({
```suggestion
    executor: (msg) => msg.channel.send(makeEmbed({
```

2022-01-07 18:52 UTC, Earthsam12 commented on src/commands/support/manualleg.ts
> +            'Please see our [documentation](https://docs.flybywiresim.com/pilots-corner/advanced-guides/flight-planning/disco/?h=manual#discontinuities-after-manual-leg) for information on how to dea
```suggestion
            `Please see our [documentation](${DISCON_DOCS_URL}) for information on how to deal with a manual leg in your flight plan.`
```

2022-01-07 18:52 UTC, Earthsam12 commented on src/commands/support/manualleg.ts
> +     })),
```suggestion
    })),
```

2022-01-08 00:12 UTC, benw202 requested changes

2022-01-08 00:12 UTC, benw202 commented on src/commands/support/manualleg.ts
> +const MANUAL_URL = 'https://cdn.discordapp.com/attachments/752801628347957248/929071827752480839/mcdu-discontinuity-manual-conceptual.png';
```suggestion
const MANUAL_LEG_IMAGE_URL = 'https://cdn.discordapp.com/attachments/752801628347957248/929071827752480839/mcdu-discontinuity-manual-conceptual.png';
```

Clears up constant naming. 'MANUAL' could be mistaken for a traditional manual etc when searching the repo.

2022-01-08 00:12 UTC, benw202 commented on src/commands/support/manualleg.ts
> +        image: { url: MANUAL_URL },
```suggestion
        image: { url: MANUAL_LEG_IMAGE_URL },
```

2022-01-08 00:12 UTC, benw202 commented on src/commands/support/manualleg.ts
> +    name: ['manualleg','vm'],
```suggestion
    name: ['manualleg', 'vm'],
```

This was suggested before, but not done.

2022-01-08 09:27 UTC, benw202 approved these changes

2022-01-08 09:28 UTC, merged