added simbriefimport.ts and updated index.ts
flybywiresim/discord-bot pull request #154
Opened 2022-02-20 22:33 UTC by nebula231

feat: Simbrief integration command

The command shows users how to use SimBrief integration, with an image showing how it will look when everything is done correctly, and to the docs referring to how to set it up.  Commands are: import, integration,  integ

<img width="636" alt="image" src="https://user-images.githubusercontent.com/88508303/154867319-f9fba87e-c408-4740-8477-29908e533ee5.png">

zx#0671

2022-02-20 23:01 UTC, benw202 requested changes
Good first command!

2022-02-20 23:01 UTC, benw202 commented on src/commands/a32nx/simbriefimport.ts
> +    description: 'Shows how to use SimBrief integration ',
```suggestion
    description: 'Shows how to use SimBrief integration',
```

Removes space

2022-02-21 17:10 UTC, benw202 approved these changes

2022-02-21 17:10 UTC, benw202 commented
LGTM!

2022-02-21 17:18 UTC, NUTTTTTTTT approved these changes
LGTM! 
![image](https://user-images.githubusercontent.com/87286435/155001529-d0d5aa91-0d41-4b7c-b725-2709c466f654.png)

2022-02-21 17:20 UTC, merged