feat: .zulu command
flybywiresim/discord-bot pull request #212
Opened 2022-04-18 00:54 UTC by Earthsam12

## Description

adds command .zulu to show the current time in a given UTC-offset timezone. this can be useful given the fact that a majority of active users have their UTC timezone in their nickname (e.g. [Z-4], [Z+11])

**NOTE:**
I have left a comment in the code regarding whether the command should use DD MMMM or MMMM DD. I would like for see what the team would prefer.

## Test Results

![image](https://user-images.githubusercontent.com/93292288/163738787-17f0bf63-0503-4539-9720-8a308ce9b1bf.png)

## Discord Username

Earthsam12#5545

2022-04-18 08:08 UTC, benw202 commented
This will probably need some error handling in it.

2022-04-19 00:21 UTC, Earthsam12 commented
> This will probably need some error handling in it.

I added a simple line to account for when `parseFloat` doesn't 'filter out' bad inputs. I couldn't find any other cases that should be handled differently, except for maybe not allowing more a than ±12 (13?) timezone

2022-04-22 19:32 UTC, benw202 approved these changes

2022-04-22 19:32 UTC, benw202 commented
LGTM!

2022-04-22 19:54 UTC, benw202 requested changes

2022-04-22 19:54 UTC, benw202 commented on src/commands/index.ts
> +    translate,
Repeated line?

2022-04-23 11:26 UTC, benw202 requested changes

2022-04-23 11:26 UTC, benw202 commented on src/commands/index.ts
> +    translate,
```suggestion
```

2022-04-23 11:27 UTC, benw202 approved these changes

2022-04-23 11:27 UTC, merged