lint: fix existing linting issues
flybywiresim/discord-bot pull request #213
Opened 2022-04-20 10:03 UTC by NathanInnes

## Description
Fixed all existing linting issues. 
- Renamed ctrl_e to cammelcase ctrlE
- Fixed sparse-array issue
- Adjusted weird string concatination in scamlogs.

## Test Results

## Discord Username

2022-04-22 19:33 UTC, benw202 approved these changes
LGTM!

2022-04-22 19:49 UTC, NUTTTTTTTT requested changes

2022-04-22 19:49 UTC, NUTTTTTTTT commented on src/commands/a32nx/ctrlE.ts
> -                ,
This line needs re-adding with `'',` to put the line break back in.

2022-04-24 19:15 UTC, NUTTTTTTTT approved these changes

2022-04-24 19:20 UTC, merged