Oceanfix
flybywiresim/discord-bot pull request #215
Opened 2022-04-23 08:49 UTC by Hypeism

feat: Lat/Long fix conversion chart 

.latlongfix or .llfix
## Test Results

![image](https://user-images.githubusercontent.com/52870481/164887545-0a0d735f-1851-4534-b368-5f443b509481.png)

## Discord Username
HowNowBrownCrow#2591

2022-04-23 08:50 UTC, Hypeism commented
SVG ![ocean_fixes](https://user-images.githubusercontent.com/52870481/164887605-1c2eaade-3910-485e-8dff-4199f9b1e105.svg)
PNG ![oceanicfixes](https://user-images.githubusercontent.com/52870481/164887608-4271d8e3-d2a1-4fd8-8e58-2bc60e77079c.png)

2022-04-23 09:53 UTC, tracernz commented
This missed the half-degree NAT waypoints. It should probably also cover what to do if there is no shorthand waypoint in the database for the one you want...

2022-04-24 06:01 UTC, Hypeism commented
https://cdn.discordapp.com/attachments/897491699167793182/967661284508192778/unknown.png

PNG ![oceanicfixes](https://user-images.githubusercontent.com/52870481/164958799-453b90ea-9ad3-40d8-a84a-879b39cfcd1c.png)
SVG ![fbw_oceanicfixes](https://user-images.githubusercontent.com/52870481/164958805-3c931973-5519-4469-872b-4e68d5b5586b.svg)
SVG layer structure: 
![image](https://user-images.githubusercontent.com/52870481/164958854-aa7d9dc3-bd22-4ca9-a656-30d5578b8281.png)

poster made in accordance with design principles here: https://github.com/flybywiresim/branding/blob/master/branding-guidelines/FBW-Brand-Identity-Handbook.pdf

2022-04-24 15:23 UTC, benw202 requested changes

2022-04-24 15:23 UTC, benw202 commented on src/commands/index.ts
> +    translate,
```suggestion
```

Repeated line? (Already in line 229)

2022-04-24 15:23 UTC, benw202 commented on src/commands/index.ts
> +
```suggestion
```

Empty line added?

2022-04-24 16:13 UTC, benw202 requested changes

2022-04-24 16:13 UTC, benw202 commented on src/commands/general/latlongfix.ts
> +
```suggestion

const LATLONG_IMAGE_URL = 'https://cdn.discordapp.com/attachments/817517626045104149/967659373054816286/unknown.png';

```

2022-04-24 16:13 UTC, benw202 commented on src/commands/general/latlongfix.ts
> +            image: { url: 'https://cdn.discordapp.com/attachments/817517626045104149/967659373054816286/unknown.png' },
```suggestion
            image: { url: LATLONG_IMAGE_URL },
```

2022-04-24 16:40 UTC, benw202 approved these changes

2022-04-24 16:40 UTC, merged