Refactor: Updated synaptic discord invite link
flybywiresim/discord-bot pull request #217
Opened 2022-04-25 02:01 UTC by nebula231

Updated synaptic.ts with the new vanity url. Aliases are still .synaptic and .syn

![image](https://user-images.githubusercontent.com/88508303/165008628-1cc21e27-4e41-4bb4-8ca3-4cbf4457a8c8.png)

zx#0671

2022-04-25 02:42 UTC, Valastiri commented
Rebased to fix PR

2022-04-25 08:39 UTC, benw202 approved these changes

2022-04-25 09:20 UTC, benw202 commented
See the comment on #216. We will remove the message delete here too!

2022-04-26 11:24 UTC, benw202 requested changes

2022-04-26 11:24 UTC, benw202 commented on src/commands/general/synaptic.ts
> +
```suggestion
```

Remove empty line

2022-04-29 23:59 UTC, NathanInnes approved these changes

2022-04-29 23:59 UTC, merged