fix: avatar command now accepts user ids
flybywiresim/discord-bot pull request #259
Opened 2022-06-08 14:28 UTC by oim1

## Description

Before this PR the avatar command did not accept user IDs. Instead it would just show the author's avatar. 

## Test Results

![image](https://user-images.githubusercontent.com/81839029/172642095-704683e1-e0fc-4189-9c30-ae67b12b2f17.png)

## Discord Username

oim#0001

2022-06-08 16:40 UTC, benw202 requested changes

2022-06-08 16:40 UTC, benw202 commented on src/commands/utils/avatar.ts
> +            title: '',
You can remove this line as you are setting a title later within your `if` statements

2022-06-10 03:48 UTC, NathanInnes commented
Please fix linting errors.

2022-06-10 06:37 UTC, NathanInnes approved these changes

2022-06-10 06:38 UTC, merged