feat: unified command permissions framework
flybywiresim/discord-bot pull request #405
Opened 2023-02-01 04:53 UTC by doosedev

## Description

This PR removes all command-specific conditionals for checking role & channel permissions, and moves them along with existing permissions to a unified checker called by the command handler.

## Test Results

WIP

## Discord Username

pererry#8489

2023-02-01 09:23 UTC, benw202 commented
Liking this so far! Nice work

2023-02-05 00:21 UTC, pdellaert requested changes
Great solution for permissions! Think I found one bug (before testing), but otherwise I have no comment on the code at this time. (All the comments you see about using the opportunity to clean up some old permissions)

It would be good to also add a section to the `CONTRIBUTING.md` on all the different permissions that can be configured for commands. Documenting the different Permission objects. Something like (I wrote this to make sure I understand the purpose myself, for testing):

* `permissions`: Optional list of all the discord permissions a user need to have.
* `permissionsError`: The message returned to the user in case they do not have all of the `permissions`. If not provided, a generic message will be returned.
* `roles`: Optional list of `Roles` the user must have at least one of. The roles that can be provided, are defined in the `constants.ts` file. 
* `rolesError`: The message returned to the user in case they do not have any of the `roles`, or if they have at least one of the `roles` in case `rolesBlacklist` is `true`. If not provided, a generic message will be returned.
* `rolesBlacklist`: Boolean to indicate if the list needs to be handled as a blacklist instead of the default whitelist behavior.
* `channels`: a list of `Channels` or `Threads` to identify in which Discord Channels or Threads this command can be executed, or is banned from being executed in case `channelsBlacklist` is set to `true`.
* `channelsError`: The message returned to the user in case the command is executed in a channel not in the `channels` list, or if it is executed in a channel that is in the `channels` list in case `channelsBlacklist` is `true`. If not provided, a generic message will be returned.
* `channelsBlacklist`: Boolean to indicate if the list needs to be handled as a blacklist instead of the default whitelist behavior.
* `quietErrors`: Boolean to indicate if permission errors should not result in a message to the user and instead should fail silently.
* `verboseErrors`: Boolean to indicate that if no specific message is provided through `permissionsError`, `rolesError` and/or `channelsError` that a verbose explanation should be provided instead of the default simple message.

But that could be done after merging this PR as well. 

_I have not done extensive testing, will do so in a follow up._

2023-02-05 00:21 UTC, pdellaert commented on src/constants.ts
> +export const PermissionsEmbedDelay = 10;
```suggestion
export const PermissionsEmbedDelay = 10;

```
Should always have a newline/linefeed at the end of a file.

2023-02-05 00:21 UTC, pdellaert commented on src/commands/utils/ping.ts
> +    requirements: { permissions: ['ManageWebhooks'] },
Not a comment on the PR, but @benw202 : Does this make sense, should we take the opportunity to change this to BOT_DEVELOPER, ADMIN & MODERATOR roles?

2023-02-05 00:21 UTC, pdellaert commented on src/commands/moderation/welcome.ts
> +    requirements: { permissions: ['BanMembers'] },
Not a comment on the PR, but @benw202 : Does this make sense, should we take the opportunity to change this to ADMIN & MODERATOR roles?

2023-02-05 00:21 UTC, pdellaert commented on src/commands/moderation/warn/warn.ts
> +        permissions: ['BanMembers'],
```suggestion
```
Not a comment on the PR, but @benw202 : I'd suggest removing the permissions, it really doesn't have much of a point with the roles there anyway.

2023-02-05 00:21 UTC, pdellaert commented on src/commands/moderation/warn/listWarnings.ts
> +        permissions: ['BanMembers'],
```suggestion
```
Not a comment on the PR, but @benw202 : I'd suggest removing the permissions, it really doesn't have much of a point with the roles there anyway.

2023-02-05 00:21 UTC, pdellaert commented on src/commands/moderation/warn/deleteWarn.ts
> +        permissions: ['BanMembers'],
```suggestion
```
Not a comment on the PR, but @benw202 : I'd suggest removing the permissions, it really doesn't have much of a point with the roles there anyway.

2023-02-05 00:21 UTC, pdellaert commented on src/commands/moderation/untimeout.ts
> +    requirements: { permissions: ['BanMembers'] },
Not a comment on the PR, but @benw202 : Does this make sense, should we take the opportunity to change this to ADMIN & MODERATOR roles?

2023-02-05 00:21 UTC, pdellaert commented on src/commands/moderation/unban.ts
> +    requirements: { permissions: ['BanMembers'] },
Not a comment on the PR, but @benw202 : Does this make sense, should we take the opportunity to change this to ADMIN & MODERATOR roles?

2023-02-05 00:21 UTC, pdellaert commented on src/commands/moderation/timeout.ts
> +    requirements: { permissions: ['BanMembers'] },
Not a comment on the PR, but @benw202 : Does this make sense, should we take the opportunity to change this to ADMIN & MODERATOR roles?

2023-02-05 00:21 UTC, pdellaert commented on src/commands/moderation/rules.ts
> +    requirements: { permissions: ['BanMembers'] },
Not a comment on the PR, but @benw202 : Does this make sense, should we take the opportunity to change this to ADMIN & MODERATOR roles?

2023-02-05 00:21 UTC, pdellaert commented on src/commands/moderation/roleassignment.ts
> +    requirements: { permissions: ['BanMembers'] },
Not a comment on the PR, but @benw202 : Does this make sense, should we take the opportunity to change this to ADMIN & MODERATOR roles?

2023-02-05 00:21 UTC, pdellaert commented on src/commands/moderation/faq.ts
> +    requirements: { permissions: ['BanMembers'] },
Not a comment on the PR, but @benw202 : Does this make sense, should we take the opportunity to change this to ADMIN & MODERATOR roles?

2023-02-05 00:21 UTC, pdellaert commented on src/commands/moderation/ban.ts
> +    requirements: { permissions: ['BanMembers'] },
Not a comment on the PR, but @benw202 : Does this make sense, should we take the opportunity to change this to ADMIN & MODERATOR roles?

This is, perhaps with unban, the only one that makes a bit of sense :)

2023-02-05 01:26 UTC, doosedev commented on src/lib/command.ts
> +    }
great catch, i must've missed this by accidental combination of the 10 millisecond delete timer and this bug 😅

2023-02-05 06:38 UTC, pdellaert requested changes
Testing showed a bug in language, which isn't in the test report itself as the test focussed on permissions itself.
![Screenshot 2023-02-04 at 10 26 30 PM](https://user-images.githubusercontent.com/942391/216805308-745f3e5a-7946-4c6b-9187-83666db82660.png)
![Screenshot 2023-02-04 at 10 30 42 PM](https://user-images.githubusercontent.com/942391/216805309-ddcba2a0-3695-4a05-b0af-ca22e9ad4a43.png)

✅ **275/275 tests passed** ✅ 
**Full test report:** 
https://docs.google.com/spreadsheets/d/1tB-z46PuOj3ARvhCOAuow2f9w1BG2jxZzDoIByoRUYk/edit?usp=sharing

2023-02-05 06:38 UTC, pdellaert commented on src/lib/command.ts
> +                errorText = `Only the ${requirements.roles.map((r) => member.guild.roles.cache.get(r).name).join(', ')} role${requirements.roles.length > 1 ? 's are' : ' is'} are allowed to use that!
```suggestion
                errorText = `Only the ${requirements.roles.map((r) => member.guild.roles.cache.get(r).name).join(', ')} role${requirements.roles.length > 1 ? 's are' : ' is'} allowed to use that!`;
```

2023-02-05 11:32 UTC, benw202 commented
@pdellaert - Agree on your comments about changing perms. Like Pererry said on Discord, I'm happy for these to be done in another PR.

@doosedev - I'm also testing today. I would agree with Straks that an entry to `contributing.md` should be added. I'd like it added in this PR please so that new/existing contribs can grab a quick understanding of new functionality and the different options within it. (Like blacklist, the different types of errors it can spit out etc.)

2023-02-07 05:19 UTC, pdellaert reviewed
Minor tweaks on the doc, but feel free to ignore those if you think it's too much.

2023-02-07 05:19 UTC, pdellaert commented on .github/CONTRIBUTING.md
> +| verboseErrors     | Boolean flag to enable a more verbose error message for failed requirement checks. Any `permissionsError`, `rolesError`, or `channelsError` will override this setting in their r
```suggestion
| Field             | Description                                                                                                                                                                                        |
|:------------------|:---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| permissions       | List of all Discord type permissions a member must have.                                                                                                                                           |
| permissionsError  | Custom error message to return for a failed permission checks. If omitted, a generic error will be returned.                                                                                       |
| roles             | List of `Roles` which a member must have at least one of, or must not have any of if blacklisted. Roles are defined in `constants.ts`.                                                             |
| rolesError        | Custom error message to return for a failed role checks. If omitted, a generic error will be returned.                                                                                             |
| rolesBlacklist    | Boolean flag to indicate whether the list of `roles` should be treated as a blacklist (defaults as whitelist).                                                                                     |
| channels          | List of `Channels` & `Threads` that the command can be executed in, or is not allowed to be executed in if blacklisted. Channels are defined in `constants.ts`.                                    |
| channelsError     | Custom error message to return for a failed channel checks. If omitted, a generic error will be returned.                                                                                          |
| channelsBlacklist | Boolean flag to indicate whether the list of `channels` should be treated as a blacklist (defaults as whitelist).                                                                                  |
| quietErrors       | Boolean flag to disable permission failure messages completely & silently fail out of command execution. Will override all other error message fields.                                             |
| verboseErrors     | Boolean flag to enable a more verbose error message for failed requirement checks. Any `permissionsError`, `rolesError`, or `channelsError` will override this setting in their respective groups. |

```
Minor edits in text (just personal suggestions). Formatting is just me being a little neurotic (feel free to ignore). And newline at the end of the file.

2023-02-07 11:34 UTC, benw202 commented
Have tested and like what has been done. I agree with the above requested changes. Give me a ping when resolved and I can approve and merge :)

2023-02-08 00:59 UTC, pdellaert approved these changes

2023-02-08 02:27 UTC, pdellaert approved these changes

2023-02-09 16:38 UTC, benw202 approved these changes

2023-02-09 16:40 UTC, merged