feat: reply to original question
flybywiresim/discord-bot pull request #414
Opened 2023-02-14 14:36 UTC by Sleinmaster

## Description

If someone adds a bot command into a reply the bot replies to the same message.

## Test Results

At the moment I have a limiting environment, will test and finish when I'm back from the holidays.

## Discord Username

Slein#8982

2023-02-20 18:18 UTC, pdellaert commented
I love this idea! I do have a few improvements/suggestions:

You'll also have to add it here: https://github.com/flybywiresim/discord-bot/blob/412138d28386b5fefc49ce8015c04abe43b5daaf/src/lib/typeCommand.ts#L111 . This is for when the multi-aircraft support is enabled and there's different replies depending on the type of aircraft. (`.airframe` for instance)

As well as here: https://github.com/flybywiresim/discord-bot/blob/412138d28386b5fefc49ce8015c04abe43b5daaf/src/lib/typeCommand.ts#L126 . As this is the case when someone executes the aircraft specific version directly (`.a32nx airframe` for instance. 

To test this, you can set this to true: https://github.com/flybywiresim/discord-bot/blob/412138d28386b5fefc49ce8015c04abe43b5daaf/src/lib/typeCommand.ts#L9

2023-02-20 18:40 UTC, Sleinmaster commented
@pdellaert 
Thanks for the suggestions.
I mainly created this pr as a reminder for myself since I could only watch the code and edit it on my phone. 
I planned to do it in the same style in all the places in that file, where a message is sent, as soon as I'm back home (next weekend).

Also I was thinking about the other cases, where the bot command is not in a reply. There I see the two possibilities to either just post the message, like now, or to reply to the message with the command in it. 
I might ask about that next week in the appropriate discord channel.

2023-02-20 19:33 UTC, pdellaert commented
@Sleinmaster , sounds good! Yeah, wasn't sure whether it was the right time to already comment. But good you are looking at it. 

No rush on this, but it is a great idea!

For the regular `CommandDefinition`, it would mean an overhaul of executors everywhere, or to define a whole new logic and replace the existing executors, which will get a lot more complex. 

Instead, I think we should focus first of moving everything to `MessageCommandDefintion` where possible. As per my investigation when I created this model, there's 2/3rds of the commands that can become `MessageCommandDefinition`, and I think there might actually be another 10% that can move. 

BenW is working on that in #406

2023-02-26 21:41 UTC, pdellaert approved these changes
### Test Results

I have one remark at the end, otherwise tests

✅ Disable multi-type - multi-typed command - direct request
✅ Disable multi-type - single-typed command - replied request
![Screenshot 2023-02-26 at 1 19 58 PM](https://user-images.githubusercontent.com/942391/221438442-cba077fe-2d0c-456a-9036-7de196d22e31.png)

✅ Enable multi-type - single-typed command - direct request
✅ Enable multi-type - multi-typed command - direct request with type a32nx
✅ Enable multi-type - multi-typed command - direct request with type a380x
![Screenshot 2023-02-26 at 1 23 07 PM](https://user-images.githubusercontent.com/942391/221438530-8e2480e3-fd16-40f9-8439-334dfc447be9.png)

✅ Enable multi-type - multi-typed command - replied request with type a32nx
✅ Enable multi-type - multi-typed command - replied request with type a380x
✅ Enable multi-type - single-typed command - replied request
![Screenshot 2023-02-26 at 1 23 19 PM](https://user-images.githubusercontent.com/942391/221438570-da4fe0ac-dd48-4f4f-a328-46d5a16cf403.png)

✅ Enabled multi-type - multi-typed command - direct request with choice
![Screenshot 2023-02-26 at 1 23 51 PM](https://user-images.githubusercontent.com/942391/221438613-418b36da-0d38-4786-bcce-a6d2222328c0.png)

✅ Enabled multi-type - multi-typed command - direct request with choice - After a32nx choice
![Screenshot 2023-02-26 at 1 24 02 PM](https://user-images.githubusercontent.com/942391/221438621-90a0219b-86ea-4aec-b6b4-c4ae21091e69.png)

✅ Enabled multi-type - multi-typed command - replied request with choice
![Screenshot 2023-02-26 at 1 25 42 PM](https://user-images.githubusercontent.com/942391/221438714-26a4b92b-377c-4e1c-8b19-5ce4fe157390.png)

✅ Enabled multi-type - multi-typed command - replied request with choice - CHOICE MADE BY COMMAND EXECUTOR
![Screenshot 2023-02-26 at 1 25 57 PM](https://user-images.githubusercontent.com/942391/221438739-dda6750c-4fa7-4a46-aa3b-3c86e5ae54da.png)

✅ Enabled multi-type - single-typed command - direct request
✅ Enabled multi-type - single-typed command - replied request
![Screenshot 2023-02-26 at 1 26 43 PM](https://user-images.githubusercontent.com/942391/221438789-3bd9b448-76f5-4031-b9b1-f624691369ef.png)

### Note on replied behavior and choice request

Currently, the `typeCommand`, when presenting a choice waits for a reaction from the _command executor_. This means that when replying to a request, and the choice is presented, the user that executes the command _must_ select the type to show the output. 

This is not a limitation of this PR, it has always been there, so this does not block this PR. I can fix this in the future by digging a bit deeper and also allowing the person who it was relied to, to react. 

Sequence to show behavior:

**Step 1** - User requests help, other user responds, choice is presented
![Screenshot 2023-02-26 at 1 38 53 PM](https://user-images.githubusercontent.com/942391/221439060-48fcc835-9f79-41ef-be8c-0f481afde252.png)

**Step 2** - User selects choice, but is not given a reply
![Screenshot 2023-02-26 at 1 39 00 PM](https://user-images.githubusercontent.com/942391/221439071-36ed691d-7a37-4cd4-ab4a-d1703b1dc339.png)

**Step 3** - Other user selects A32, choice is locked and message replaced (with proper reply)
![Screenshot 2023-02-26 at 1 39 10 PM](https://user-images.githubusercontent.com/942391/221439096-fa801dd6-6c5d-4330-937d-2abc9535f662.png)

2023-02-27 09:35 UTC, Sleinmaster commented
> Currently, the typeCommand, when presenting a choice waits for a reaction from the command executor. This means that when replying to a request, and the choice is presented, the user that executes the command must select the type to show the output.
> 
> This is not a limitation of this PR, it has always been there, so this does not block this PR. I can fix this in the future by digging a bit deeper and also allowing the person who it was relied to, to react.

That I can add fairly easy. I will change that quickly when I have time in this PR.

2023-03-03 10:40 UTC, benw202 commented
Just going to ping the CS team with this before it is merged to make sure they are happy as this will change how the bot reacts/might be used in support.

2023-03-04 12:28 UTC, Sleinmaster commented
![Screenshot 2023-03-04 131443](https://user-images.githubusercontent.com/79196358/222901053-7b52a6ac-ef83-4fa1-bd11-00e4ed0421f4.png)
![Screenshot 2023-03-04 131645](https://user-images.githubusercontent.com/79196358/222901054-6098cf58-a19e-4e8a-bb94-16ff1d0f825b.png)

For the added user ID's (only if not replied to executor)

2023-03-04 13:45 UTC, benw202 commented on src/lib/command.ts
> +            embed.setFooter({ text: `${existingFooterText} executed by ${msg.author.tag} - ${msg.author.id}` });
```suggestion
            embed.setFooter({ text: `${existingFooterText} Executed by ${msg.author.tag} - ${msg.author.id}` });
```

2023-03-04 13:55 UTC, benw202 commented
@pdellaert - have re-requested your review on this as you've been more involved :)

2023-03-06 05:15 UTC, pdellaert requested changes
There's a bug ;). Will test again once fixed.

2023-03-06 05:15 UTC, pdellaert commented on src/lib/typeCommand.ts
> +import { CommandDefinition, isMessageCommand, MessageCommandDefinition, hasRequiredPermissions, sendPermissionsEmbed, replyToMessage, replyToCommandOrQuestion } from './command';
```suggestion
import { CommandDefinition, isMessageCommand, MessageCommandDefinition, hasRequiredPermissions, sendPermissionsEmbed, replyToCommandOrQuestion } from './command';
```
`replyToMessage` no longer exists and will cause a compile error.

2023-03-06 05:19 UTC, pdellaert reviewed
Looks good, will do another test run and approve once done

2023-03-06 05:43 UTC, pdellaert commented
### Test Results

I have one remark at the end which is not of any impact on this PR, otherwise tests are all good!

✅ Disable multi-type - multi-typed command - direct request
✅ Disable multi-type - single-typed command - replied request
<img width="608" alt="Screenshot 2023-03-05 at 9 22 02 PM" src="https://user-images.githubusercontent.com/942391/223025497-e96b9c5c-d2a0-478d-9cdc-6af978416358.png">

✅ Enable multi-type - single-typed command - direct request
✅ Enable multi-type - multi-typed command - direct request with type a32nx
✅ Enable multi-type - multi-typed command - direct request with type a380x
<img width="613" alt="Screenshot 2023-03-05 at 9 23 53 PM" src="https://user-images.githubusercontent.com/942391/223025716-9a0f244f-df67-46cd-a930-c8bb64002b3d.png">

✅ Enable multi-type - multi-typed command - replied request with type a32nx
✅ Enable multi-type - multi-typed command - replied request with type a380x
<img width="605" alt="Screenshot 2023-03-05 at 9 26 48 PM" src="https://user-images.githubusercontent.com/942391/223026080-2640655b-d290-453f-be11-fcb54dbbe4d3.png">

✅ Enable multi-type - single-typed command - replied request
<img width="589" alt="Screenshot 2023-03-05 at 9 27 13 PM" src="https://user-images.githubusercontent.com/942391/223026140-605a472f-ae55-4057-a2d4-5ccf3bd5d5ab.png">

✅ Enabled multi-type - multi-typed command - direct request with choice
<img width="613" alt="Screenshot 2023-03-05 at 9 30 31 PM" src="https://user-images.githubusercontent.com/942391/223026903-190e96fa-482c-4a5c-8d19-bc05c9b1e001.png">

❌❌❌❌❌❌❌❌❌❌
❌ Enabled multi-type - multi-typed command - direct request with choice - After a32nx choice made by original user
<img width="603" alt="Screenshot 2023-03-05 at 9 30 44 PM" src="https://user-images.githubusercontent.com/942391/223026620-fb3f2cc8-8874-4727-bc4a-980d101caac8.png">

Failure: Multiple "executed by"

❌❌❌❌❌❌❌❌❌❌
❌ Enabled multi-type - multi-typed command - replied request with choice - Choice made by Command executor
<img width="429" alt="Screenshot 2023-03-05 at 9 33 27 PM" src="https://user-images.githubusercontent.com/942391/223026979-96a3d5ce-7dd6-4a35-b5af-1c8ed3aa05d9.png">

Failure: Multiple "executed by"

❌❌❌❌❌❌❌❌❌❌
❌ Enabled multi-type - single-typed command - direct request
❌ Enabled multi-type - single-typed command - replied request
<img width="592" alt="Screenshot 2023-03-05 at 9 35 39 PM" src="https://user-images.githubusercontent.com/942391/223027231-38bec8c2-05a6-4b20-a93a-759823e2cf65.png">

Failure: Multiple "executed by"

### Bug

Interesting bug with the multiple footers. The reason seems that the existingFooterText variable remains set across command executions, then the catch doesn't clear it, so it kept an existing footer and re-used it. I have a proposal to fix this with some small enhancements as well.

2023-03-06 05:50 UTC, pdellaert requested changes
Fixing the bug found during testing

2023-03-06 05:50 UTC, pdellaert commented on src/lib/command.ts
> +}
```suggestion
export async function replyToCommandOrQuestion(msg: Message, embed: EmbedBuilder) : Promise<Message<boolean>> {
    let existingFooterText = '';
    return msg.fetchReference()
        .then((res) => {
            const existingFooter = embed.data.footer;
            if (existingFooter) {
                existingFooterText = existingFooter.text;
            }
            embed.setFooter({ text: `${existingFooterText}\n\nExecuted by ${msg.author.tag} - ${msg.author.id}` });
            return res.reply({ embeds: [embed] });
        })
        .catch(() => msg.reply({ embeds: [embed] }));
}
```

This fixes the bug in my last testing and cleans up the text a bit as well (no unnecessary space)

2023-03-06 07:30 UTC, pdellaert requested changes

2023-03-06 07:30 UTC, pdellaert commented on src/lib/command.ts
> +            embed.setFooter({ text: `${existingFooterText} Executed by ${msg.author.tag} - ${msg.author.id}` });
Sorry about previous posts, brainfart. Here's the issue, you update the embed in place, which updates the embed system wide with this footer. So every time this is executed, it adds a new line 

Examples:
<img width="587" alt="Screenshot 2023-03-05 at 11 27 16 PM" src="https://user-images.githubusercontent.com/942391/223045650-cb4f4d46-eef5-4d09-948d-6e41d080f72a.png">
<img width="587" alt="Screenshot 2023-03-05 at 11 27 23 PM" src="https://user-images.githubusercontent.com/942391/223045657-bf78120f-d91d-4cb5-aec1-b820b5cf2700.png">
<img width="599" alt="Screenshot 2023-03-05 at 11 27 41 PM" src="https://user-images.githubusercontent.com/942391/223045658-a28a43c2-3237-41a8-afda-32d595581d1a.png">

2023-03-11 19:43 UTC, benw202 approved these changes
LGTM! Thanks for the addition :)

2023-03-11 19:46 UTC, merged