feature: command for tca key binding problems
flybywiresim/discord-bot pull request #432
Opened 2023-03-21 20:43 UTC by Sleinmaster

## Description

Adds a new command .tca to give a hint to remove all unused key bindings if the tca quadrant is used without the add-ons

## Test Results

Tested without the image. Image and text certainly need some improvement:
![image](https://user-images.githubusercontent.com/79196358/226735933-f32de8d5-4373-401e-8135-c5dcc14f0f3f.png)

## Discord Username

Slein#8982

2023-03-22 05:20 UTC, pdellaert commented
Only comment I have would be : Do we need each sentence on a single line, or can we just make it a single paragraph/line? (same text still). 

Screenshot: Will need to find an example of the default configuration. Might check if I can get that happen somehow.

2023-03-23 03:42 UTC, pdellaert reviewed
We might want to change the image to higher quality and perhaps without the throttle itself? Maybe I'll look into it this weekend and also look at the doc side. Then we can merge it together.

2023-03-23 03:42 UTC, pdellaert commented on src/commands/support/tca.ts
> +const TCA_URL = `${process.env.IMAGE_BASE_URL}support/tca-settings.png`;
filename of the image is different from the actual name.

2023-04-15 15:03 UTC, benw202 commented
@Sleinmaster - Test results state image and text need improvement, is this still the case or is this PR ready to go?

2023-04-15 17:54 UTC, pdellaert requested changes
Small change and image update, otherwise ready to go!

2023-04-15 17:54 UTC, pdellaert commented on src/commands/support/tca.ts
> +        'The default controller settings in MSFS always includes the key bindings for the add-on axis and buttons aswell which can cause problems if the add-ons are not connected, e.g., automatically
```suggestion
        'The default controller settings in MSFS always includes the key bindings for the add-on axis and buttons, which can cause problems if the add-ons are not connected, e.g., automatically deploying full flaps, especially after pausing the sim.',
```
Minor suggestion

2023-04-15 17:54 UTC, pdellaert commented on assets/images/support/tca-settings.png
Propose to use this slightly scaled down and optimized version
![tca-settings_optimized](https://user-images.githubusercontent.com/942391/232245449-e09b3afb-0bd6-417e-9494-52b6ba94d212.png)

2023-04-15 18:21 UTC, Sleinmaster commented
@benw202 
New screenshot
![image](https://user-images.githubusercontent.com/79196358/232246810-37777595-1b54-4e2c-9709-2dca6adec899.png)

@pdellaert thanks for the review and the new image, just wanted to ask you.

2023-04-15 20:33 UTC, pdellaert approved these changes
I'll let Ben do the final check, but looking good here! (Does need a date for the changelog, but that can be done right before merging)

2023-04-16 19:01 UTC, merged