feat: simbriefdata command
flybywiresim/discord-bot pull request #443
Opened 2023-04-05 16:43 UTC by Sleinmaster

## Description

Shows a number of attributes of the last generated flightplan from simbrief, which might be helpfull as info for the user and for support.
## Test Results

![image](https://user-images.githubusercontent.com/79196358/230386037-deb8b668-6f04-4eb3-9d5c-594cd99cc40e.png)

## Discord Username

Slein#8982

2023-04-06 13:27 UTC, Sleinmaster commented
Works with user ID and username, shows a message if the user ID is someone else's username.

2023-04-15 20:47 UTC, pdellaert requested changes
Proposing consistent use of the proper application/brand name of SimBrief.

2023-04-15 20:47 UTC, pdellaert commented on src/commands/utils/simbriefdata.ts
> +    title: 'Simbrief Data',
```suggestion
    title: 'SimBrief Data',
```

2023-04-15 20:47 UTC, pdellaert commented on src/commands/utils/simbriefdata.ts
> +    title: 'Simbrief Data',
```suggestion
    title: 'SimBrief Data',
```

2023-04-15 20:47 UTC, pdellaert commented on src/commands/utils/simbriefdata.ts
> +        `Entered userId ${enteredId} and returned userId ${flightplanId} don't match. The UserId might be used as username by someone else.`,
```suggestion
        `Entered userId ${enteredId} and returned userId ${flightplanId} don't match. The userId might be used as username by someone else.`,
```

2023-04-15 20:47 UTC, pdellaert commented on src/commands/utils/simbriefdata.ts
> +    title: 'Simbrief Error',
```suggestion
    title: 'SimBrief Error',
```

2023-04-15 20:47 UTC, pdellaert commented on src/commands/utils/simbriefdata.ts
> +    description: makeLines(['Simbriefdata could not be read.', errorMessage]),
```suggestion
    description: makeLines(['SimBrief data could not be read.', errorMessage]),
```

2023-04-15 20:47 UTC, pdellaert commented on src/commands/utils/simbriefdata.ts
> +    description: 'Provides infos to the most recent simbrief flightplan',
```suggestion
    description: 'Provides infos to the most recent SimBrief flightplan',
```

2023-04-15 20:47 UTC, pdellaert commented on .github/command-docs.md
> +| .simbiefdata | Lists a number of attributes from the last generated simbrief flightplan of a user   | ---                                                            |
```suggestion
| .simbiefdata | Lists a number of attributes from the last generated SimBrief flightplan of a user   | ---                                                            |
```

2023-04-15 20:57 UTC, pdellaert approved these changes

2023-05-01 17:31 UTC, pdellaert requested changes
Pretty happy, but we should capture the empty/non-existing simbrief id to be safe.

2023-05-01 17:31 UTC, pdellaert commented on .github/command-docs.md
> +| .simbiefdata | Lists a number of attributes from the last generated SimBrief flightplan of a user   | ---                                                            |
Can you add a doc item for `.simbriefdatarequest`?

2023-05-01 17:31 UTC, pdellaert commented on src/commands/utils/simbriefdata.ts
Empty simbrief ID should capture a simple help message that an ID needs to be provided:
<img width="608" alt="Screenshot 2023-05-01 at 10 28 59 AM" src="https://user-images.githubusercontent.com/942391/235497163-1b667fa3-b086-40f0-a193-69e22f0c89f8.png">

2023-05-01 17:55 UTC, benw202 commented on src/commands/utils/simbriefdata.ts
Why don't we combine these commands?

`.simbriefdata` with no ID entry could send what `.simbriefdatarequest` sends? Acting as the help and Privacy Notice

`.simbriefdata` with ID entry does as it does now.

This would eliminate the need of another command keeping the bot + commands list 'cleaner'?

cc: @Sleinmaster

2023-05-01 17:57 UTC, pdellaert commented on src/commands/utils/simbriefdata.ts
Yeah, like that idea, then the doc comment is irrelevant, of course.

2023-05-03 15:55 UTC, Sleinmaster commented on src/commands/utils/simbriefdata.ts
![image](https://user-images.githubusercontent.com/79196358/235970825-ab2c5fb8-e9a8-41c8-823c-20405e9e5814.png)

2023-05-08 04:16 UTC, pdellaert approved these changes

2023-05-08 04:17 UTC, pdellaert approved these changes

2023-05-08 04:18 UTC, merged