Feat(cmd) add .remoteefb command
flybywiresim/discord-bot pull request #464
Opened 2023-06-03 18:17 UTC by Lauvaan

## Description

Fixes: #460 

Adds a command describing the situation of remote acces of the efb, more info in #460 

## Test Results

## Discord Username

Lauvaan#3330

2023-06-03 19:20 UTC, pdellaert requested changes
Two small changes to look into, otherwise looks good (have not tested yet, but I'm fairly sure it'll be fine)

Needs a CHANGELOG entry too, so that'll block the merge until provided.

2023-06-03 19:20 UTC, pdellaert commented on .github/command-docs.md
> +| .remoteefb            | Provides information about to the viewing the EFB remotely                                   | .refb <br> .remoteflypad <br> .rflypad           |
Your `|` aren't lining up with the others, which you should (use spaces, not tabs, in your editor, just to be save)

2023-06-03 19:20 UTC, pdellaert commented on src/commands/support/remoteEfb.ts
> +        'In the meantime, you can however use an application like [Spacedesk](https://www.spacedesk.net/)* to create a virtual screen using yout tablet/phone/pc, and then de-attach the EFB from MSFS
```suggestion
        'In the meantime, you can however use an application like [Spacedesk](https://www.spacedesk.net/)* to create a virtual screen using your tablet/phone/pc, and then de-attach the EFB from MSFS by holding the ALTGR button and clicking on the EFB with your mouse. You can then drag the EFB window to your virtual screen. Please note that this solution will degrade your performance slightly, as your computer needs to render and process the new virtual screen.',
```
Small typo correction.

2023-06-05 17:52 UTC, benw202 commented on src/commands/index.ts
> +import { remoteEfb } from './support/remoteEfb';
This should go at the end of the list

2023-06-05 17:52 UTC, benw202 commented on src/commands/index.ts
> +    remoteEfb,
This should go at the end of the list

2023-06-12 16:01 UTC, benw202 approved these changes

2023-06-12 16:03 UTC, merged