fix: typo to .simbriefdata in the list of commands
flybywiresim/discord-bot pull request #472
Opened 2023-06-13 20:32 UTC by JasonO99

## fix: typo to .simbriefdata in the list of commands Title

## Description

Currently shows .simbiefdata which is incorrect. Corrected to .simbriefdata as per the actual command.

## Test Results

N/A - This is not a change to the Discord Bot command itself, only to the document listing the commands.

## Discord Username

jason_91

2023-06-13 20:38 UTC, Sleinmaster approved these changes

2023-06-14 02:49 UTC, Valastiri commented
Simple enough change -- haven't been around in the repo in a while so I won't do a merge but will approve all :)

2023-06-14 02:50 UTC, Valastiri approved these changes

2023-06-27 22:21 UTC, NUTTTTTTTT requested changes
Can you add a changelog entry for this please, otherwise LGTM (and update branch if you can, otherwise can do it from this end)

2023-06-27 23:47 UTC, NUTTTTTTTT approved these changes

2023-06-27 23:48 UTC, merged