chore: remove the experimental version
flybywiresim/discord-bot pull request #474
Opened 2023-06-27 19:47 UTC by Sleinmaster

## Description

Remove the experimental version as it's being discontinued.
Change Text of .experimental to reflect the discontinuation.

## Test Results

![image](https://github.com/flybywiresim/discord-bot/assets/79196358/28c2c0d2-51b3-44fd-b979-01871492dbca)

## Discord Username

slein15

2023-06-27 22:28 UTC, NUTTTTTTTT commented
Dropped you a line on discord regarding the changes to .exp, will do full review following that discussion.

2023-06-28 05:58 UTC, Valastiri requested changes
corrections

2023-06-28 05:58 UTC, Valastiri commented on src/commands/aircraft/weather.ts
> +        'The terrain map (TERR on ND) is currently only available on the development version via [SimBridge.](https://docs.flybywiresim.com/simbridge/)',
```suggestion
        'The terrain map (TERR on ND) is currently only available on the Stable + Development versions via [SimBridge.](https://docs.flybywiresim.com/simbridge/)',
```

2023-06-28 05:58 UTC, Valastiri commented on src/commands/general/installer.ts
> +    description: 'Download the A32NX Installer where you can select either the Stable or Developer Version, and download and install the addon directly into your Community Folder, [download here](htt
```suggestion
    description: 'Download the A32NX Installer where you can select either the Stable or Development Version, and download and install the addon directly into your Community Folder, [download here](https://api.flybywiresim.com/installer)',
```

2023-06-28 05:58 UTC, Valastiri commented on src/commands/moderation/faq.ts
> +                value: `> We have three versions, Stable and Development (Master). The Stable version is a 'snapshot' of the development which we regard as stable with the current version of the simu
```suggestion
                value: `> We have two versions, Stable and Development (Master). The Stable version is a 'snapshot' of the development which we regard as stable with the current version of the simulator. The Development build is updated daily and is a constant work in progress and although we test each update thoroughly, minor issues may occur from time to time. If you find this to be the case, you can report these issues in <#${Channels.A32NX_SUPPORT}>.`,
```

2023-06-28 06:02 UTC, Sleinmaster commented on src/commands/aircraft/experimental.ts
> +        'The function of the Experimental version is to test high-impact features which aren't ready for the wider public yet. As there are currently no such features being tested and it being easier
```suggestion
        'The function of the Experimental version is to test high-impact features which aren\'t ready for the wider public yet. As there are currently no such features being tested and it being easier to introduce new features into the Development version and maintain it, it was decided to put the Experimental version on hold.',
```

2023-06-28 06:03 UTC, Sleinmaster commented on src/commands/aircraft/weather.ts
> +        'The terrain map (TERR on ND) is currently only available on the development version via [SimBridge.](https://docs.flybywiresim.com/simbridge/)',
```suggestion
        'The terrain map (TERR on ND) is available on all versions via [SimBridge.](https://docs.flybywiresim.com/simbridge/)',
```

2023-06-28 06:09 UTC, Valastiri approved these changes

2023-06-28 11:21 UTC, NUTTTTTTTT commented
Great changes, thanks for this!

2023-06-28 11:21 UTC, merged