feat(cmd): .simbridgedebug command
flybywiresim/discord-bot pull request #478
Opened 2023-06-29 10:39 UTC by Lauvaan

## Description

Fixes: #473 

A command that explains the reason for simbridge crashing, and provides steps to send a screenshot that support can use to debug the situation.

## Test Results

N/A for now

## Discord Username

2023-06-29 10:40 UTC, Lauvaan commented
Going to get screenshots and add changelog after I get back home, now have only chromebook and github.dev, so can't take the screenshots.

2023-07-27 13:07 UTC, pdellaert commented
@Lauvaan, can you add a CHANGELOG entry? and have a quick look at the lint error? (seems like there's unnecessary escapes)

2023-07-27 13:14 UTC, Lauvaan commented
> @Lauvaan, can you add a CHANGELOG entry? and have a quick look at the lint error? (seems like there's unnecessary escapes)

Yep, gonna do it on the weekend probably, if I have time

2023-08-07 17:04 UTC, NUTTTTTTTT requested changes
Aside from this, LGTM x

2023-08-07 17:04 UTC, NUTTTTTTTT commented on src/commands/support/simbridgeDebug.ts
> +        '3. Type `fbw-simbridge.exe` and press enter',
```suggestion
        '3. Type `fbw-simbridge.exe` and press enter.',
```

2023-08-07 21:17 UTC, benw202 commented
> Aside from this, LGTM x

Thanks! Can you merge when approved pls

2023-08-27 14:35 UTC, merged