feat: Add DirectX 12 command
flybywiresim/discord-bot pull request #95
Opened 2021-11-19 01:34 UTC by Earthsam12

## Description

Since the release of Sim Update 7 and the addition of DirectX 12 support, the server has received many questions regarding it.
This PR adds a simple explanation command of the current state of MSFS, FBW and DX12 via ".dx12".

## Test Results

![image](https://user-images.githubusercontent.com/93292288/142540203-0fb64c5d-d457-44a9-b61f-4dd8efdb7754.png)

## Discord Username

Earthsam12#5545

2021-11-19 04:15 UTC, oim1 commented
I feel like this would be better under the 'support' category instead of general. Someone correct me if they feel like general is appropriate.

2021-11-19 14:46 UTC, Earthsam12 commented
> I feel like this would be better under the 'support' category instead of general. Someone correct me if they feel like general is appropriate.

Ok I can do this later today.

Also, do you think that I should add clarification about how DX12 doesn't have any performance increase? I've seen more of those questions in the server too.

2021-11-19 19:08 UTC, benw202 commented
@Earthsam12 Performance is sometimes a bit of a grey area as users have a whole host of different hardware/configurations etc. If you feel it is mandatory/people are asking a lot, you could say your results may vary bla bla, but maybe not give a solid 'no' to it?

2021-11-19 19:36 UTC, Earthsam12 commented
> @Earthsam12 Performance is sometimes a bit of a grey area as users have a whole host of different hardware/configurations etc. If you feel it is mandatory/people are asking a lot, you could say your results may vary bla bla, but maybe not give a solid 'no' to it?

I think I'll just leave it as is then, since the main point of the command is about the FBW addon with DX12, rather than the sim in general. 
I'll commit to move the command to src/commands/support in just a moment

2021-11-19 23:02 UTC, tracernz commented
Instead of saying there's an issue with it, maybe something like:
> Microsoft is offering a preview of DirectX 12 support from Sim Update 7 (November 2021). FlyByWire cannot offer support for users of the DirectX 12 preview at this time. If you do decide to experiment, please ensure you test with DirectX 11 prior to reporting any issues.

2021-11-20 21:14 UTC, Earthsam12 commented
> Instead of saying there's an issue with it, maybe something like:
> > Microsoft is offering a preview of DirectX 12 support from Sim Update 7 (November 2021). FlyByWire cannot offer support for users of the DirectX 12 preview at this time. If you do decide to experiment, please ensure you test with DirectX 11 prior to reporting any issues.

The issue with DX12 is the stuttering with glass cockpit tech in the FBW, so it would be counter productive to advise users that they can experiment with it as they would likely end up coming back asking for support and wasting time, defeating the purpose of the command.

2021-11-23 09:56 UTC, benw202 requested changes

2021-11-23 09:57 UTC, benw202 commented on src/commands/support/directx12.ts
> +                + 'This is not a FBW issue and we cannot address it for now - please keep in mind DX12 is officially a "beta feature" and thus should not be used unless you know what you are doing. '
Could be useful to say that we won't provide support?

2021-11-23 14:28 UTC, benw202 approved these changes

2021-11-23 14:28 UTC, merged